### ISSUE TITLE
Migrate to the Orka API

### ISSUE THREAD

**Issue by jpraczyk** [AndrewFarley/packer-builder-macstadium-orka#1]
First of all, thank you for bootstrapping the base for a MacStadium Orka builder!
You've mentioned in the TODO section of README, that you intent to migrate this builder to the Orka API, the documentation can be found [here](https://orkadocs.macstadium.com/docs/downloads#orka-rest-api)
While I'm not a Golang developer myself, I'm posting this issue for visibility 😃

**Comment by AndrewFarley** [comment]
Thanks, I believe they had not published this API documentation when I started and posted this project, MacStadium actually reached back out to me last week and sent me a direct link to their api documentation so I could get going on this, and now it looks like they shared it publicly as well, which is exciting!

I will be iterating on this in the coming weeks, as I begin to use it more and more.  I will definitely want to use the API directly, specifically for the issue of getting the ID of the VM we just launched (which their CLI doesn't do, boooo).  :P

Thanks for reaching out and sharing this @jpraczyk
