### ISSUE TITLE
Project Maintenance Future

### ISSUE THREAD

**Issue by farvour** [AndrewFarley/packer-builder-macstadium-orka#5]
Hey @AndrewFarley I know you were working on this. I was curious as to whether you think you will be able to maintain this moving forward? This was an awesome start to get going with Orka and MacStadium. However, I'm not sure if you are still working with customers who use MacStadium? If you do or think you will great, disregard. If not, I was just curious if you still wanted to maintain this project or dedicate your time to it - I forked a copy over in lumoslabs and wouldn't mind maintaining it for the time being since we're actively using it.

I submitted a couple of pull requests if you have time to review. :-)

**Comment by AndrewFarley** [comment]
@farvour I'm happy to continue supporting this and reviewing/approving PRs.  I do not have a personal account at the moment but I've requested one and will be able to actually validate your PRs soon.  Keep shipping your PRs if you wish to pivot over to using their API, I'm sure myself and others will be quite happy for the change.
